# Generated by Django 3.1.5 on 2021-12-18 13:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='', upload_to='media/explore/')),
                ('important_dates', ckeditor.fields.RichTextField(default='')),
                ('how_to_apply', ckeditor.fields.RichTextField(default='')),
                ('syllabus', ckeditor.fields.RichTextField(default='')),
                ('slug_exam', models.CharField(default='', max_length=50)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.category')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='', upload_to='media/explore')),
                ('pub_date', models.DateField(default='now')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='UserNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.new')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Name of exam qualifier', max_length=50)),
                ('image', models.ImageField(default='', upload_to='media/explore/')),
                ('short_description', ckeditor.fields.RichTextField(default='')),
                ('strategy', ckeditor.fields.RichTextField(default='')),
                ('slug_strategy', models.CharField(default='', max_length=50)),
                ('exam_qualified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
    ]
