# Generated by Django 3.1.5 on 2021-12-18 13:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.IntegerField(default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug_chapter', models.CharField(default='', max_length=50)),
                ('exam_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='media/courses/thumbnails/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resource', models.FileField(blank=True, upload_to='media/courses/notes/')),
                ('length', models.IntegerField()),
                ('educator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.educator')),
            ],
        ),
        migrations.CreateModel(
            name='Guider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('Image', models.ImageField(default='', upload_to='media/guider/')),
                ('achievements', ckeditor.fields.RichTextField(default='')),
                ('slug_guider', models.CharField(default='', max_length=50)),
                ('Exam_qualified', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
            options={
                'ordering': ['name', 'Exam_qualified'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('standard', models.IntegerField(blank=True, default='')),
                ('slug_subject', models.CharField(default='', max_length=50)),
                ('exam_name', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
            options={
                'ordering': ['name', 'exam_name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('serial_number', models.IntegerField()),
                ('video_id', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, upload_to='media/courses/videos/')),
                ('is_preview', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=100000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='UserDoubt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('doubt_text', models.TextField(blank=True, max_length=820)),
                ('doubt_image', models.ImageField(null=True, upload_to='media/doubts')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('waitage_in_exam', models.CharField(default='', max_length=500)),
                ('notes', ckeditor.fields.RichTextField(default='')),
                ('quesitions_and_solutions', ckeditor.fields.RichTextField(default='')),
                ('slug_topic', models.CharField(default='', max_length=50)),
                ('chapter_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('designed_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.guider')),
                ('exam_name', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('sub_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
            ],
            options={
                'ordering': ['name', 'designed_by'],
            },
        ),
        migrations.CreateModel(
            name='Quesions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default='')),
                ('Quesion', ckeditor.fields.RichTextField(default='')),
                ('solution', ckeditor.fields.RichTextField(default='')),
                ('slug_quesition', models.CharField(default='', max_length=50)),
                ('exam_name', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('topic', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.topic')),
            ],
            options={
                'ordering': ['marks', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubtSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=50000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_free', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.userdoubt')),
                ('solved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.guider')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
        ),
    ]
