# Generated by Django 3.1.5 on 2021-12-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211224_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
