# Generated by Django 3.1.5 on 2022-01-01 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_payment_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='designed_by',
        ),
        migrations.AddField(
            model_name='chapter',
            name='designed_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.guider'),
        ),
    ]
