# Generated by Django 3.1.5 on 2022-01-25 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_materials_materialsource_matterialtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
