# Generated by Django 3.1.5 on 2021-12-18 13:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Oppotunitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='', upload_to='media/explore/')),
                ('slug', models.CharField(max_length=50)),
                ('suggested_by', models.CharField(default='', max_length=50)),
                ('exam_to_qualify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Career_Oppotunitie_Comment',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.career_oppotunitie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Common_strategie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.CharField(max_length=50)),
                ('suggested_by', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='media/explore/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Oppotunitie_Comment_Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reply', models.TextField(max_length=500)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.career_oppotunitie_comment')),
            ],
        ),
        migrations.CreateModel(
            name='Common_strategieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('common_strategies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.common_strategie')),
            ],
        ),
        migrations.CreateModel(
            name='Career_OppotunitieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('career_oppotunities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.career_oppotunitie')),
            ],
        ),
    ]
