# Generated by Django 3.1.5 on 2021-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211219_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.TextField(max_length=80000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
