# Generated by Django 3.1.5 on 2021-12-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211222_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogads',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='strategyquesition',
            options={'ordering': ['-time']},
        ),
    ]
