# Generated by Django 3.1.5 on 2022-01-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/educator/'),
        ),
    ]
