# Generated by Django 3.1.5 on 2022-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_educator_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('Phone_No', models.PositiveIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='media/applications')),
            ],
        ),
    ]
