# Generated by Django 3.1.5 on 2021-12-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(help_text='mock test, concept booster, challenger,  topicwise, etc.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_timed', models.BooleanField(default=True)),
                ('is_preview', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=500)),
                ('no_of_quesitions', models.IntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.category')),
            ],
        ),
        migrations.CreateModel(
            name='quizTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseries.quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='quiz type for exam,', max_length=50)),
                ('description', models.TextField(help_text='must include our features of our website', max_length=5000)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='media/tests/thumbnails/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('no_of_quizes', models.IntegerField()),
                ('designed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.educator')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Quesition',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('quesition', models.TextField(max_length=808)),
                ('option_1', models.CharField(max_length=80)),
                ('option_2', models.CharField(max_length=80)),
                ('option_3', models.CharField(max_length=80)),
                ('option_4', models.CharField(max_length=80)),
                ('correct', models.CharField(max_length=88)),
                ('quizcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseries.quizcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testseries.quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
