# Generated by Django 3.1.5 on 2021-12-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizcourse',
            name='slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
