# Generated by Django 3.1.5 on 2021-12-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0002_auto_20211220_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prerequisite',
            new_name='quizPrerequisite',
        ),
    ]
