# Generated by Django 3.1.5 on 2021-12-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0003_auto_20211220_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesition',
            name='quiz',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='testseries.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='testseries.quizcourse'),
        ),
    ]
