# Generated by Django 3.1.5 on 2021-12-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0005_userresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesition',
            name='solution',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
