# Generated by Django 3.1.5 on 2021-12-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0006_quesition_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponses',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
