# Generated by Django 3.1.5 on 2021-12-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0007_userresponses_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponses',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='userresponses',
            name='correct',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
