# Generated by Django 3.1.5 on 2021-12-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0008_auto_20211225_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponses',
            name='correct',
        ),
        migrations.AddField(
            model_name='userresponses',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
