# Generated by Django 3.1.5 on 2021-12-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testseries', '0009_auto_20211225_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesition',
            name='solution',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
